<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodingSeb.Localization" Version="1.4.0" />
        <PackageReference Include="CodingSeb.Localization.Avalonia" Version="1.4.1" />
        <PackageReference Include="CodingSeb.Localization.JsonFileLoader" Version="1.4.0" />
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0"/>
        <PackageReference Include="NUnit" Version="4.3.2"/>
        <PackageReference Include="NUnit.Analyzers" Version="4.7.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" Version="5.0.0"/>
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-dev-02318" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EnigmaWin\EnigmaWin.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\EnigmaWin\Resources\swedll64.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ViewModels\" />
    </ItemGroup>

</Project>
