// StarDefinitions.cs
// EnigmaApl is open source. For more information see se_license.html and License, both at the root of the application.
// Created by Jan Kampherbeek 2026.

using System.Collections.Generic;

namespace EnigmaWin.Sources.Features.Radix.RadixAnalysis.FixStars;

public readonly record struct StarSelectionMembership(bool InPtolemy, bool InRobson, bool InBrady);

public sealed record StarDefinitions(
    string Id,
    string Name,
    string AstronomicalName,
    IReadOnlyList<string> Aliases,
    StarSelectionMembership SelectionMembership,
    double Magnitude)
{
    private static List<StarDefinitions>? _allCases;

    public static IReadOnlyList<StarDefinitions> AllCases => _allCases ??= BuildAll();

    private static List<StarDefinitions> BuildAll() => new()
    {
        new("aldebaran",   "Aldebaran",                "alTau",      [],                                    new(true,  true,  true), 0.985),
        new("algol",       "Algol",                    "bePer",      [],                                    new(true,  true,  true), 2.12),
        new("antares",     "Antares",                  "alSco",      [],                                    new(true,  true,  true), 1.09),
        new("regulus",     "Regulus",                  "alLeo",      [],                                    new(true,  true,  true), 1.35),
        new("sirius",      "Sirius",                   "alCMa",      [],                                    new(true,  true,  true), -1.47),
        new("spica",       "Spica",                    "alVir",      [],                                    new(true,  true,  true), 1.04),
        new("galCenter",   "Gal. Center",              "SgrA*",      [],                                    new(false, false, false), 999.99),
        new("greatAttractor", "Great Attractor",       "GA",         [],                                    new(false, false, false), 999.99),
        new("virgoCluster",   "Virgo Cluster",         "VC",         [],                                    new(false, false, false), 999.99),
        new("andromedaGalaxy","Andromeda Galaxy",      "M31",        [],                                    new(false, true,  false), 3.44),
        new("praesepeCluster","Praesepe Cluster",      "M44",        [],                                    new(false, true,  false), 3.7),
        new("polaris",     "Polaris",                  "alUMi",      [],                                    new(false, true,  true), 2.005),
        new("sanduleak",   "Sanduleak",                "SN1987A",    [],                                    new(false, false, false), 4.81),
        new("deneb",       "Deneb",                    "alCyg",      ["Deneb Adige"],                       new(true,  true,  true), 1.25),
        new("rigel",       "Rigel",                    "beOri",      [],                                    new(true,  true,  true), 0.12),
        new("mira",        "Mira",                     "omiCet",     [],                                    new(false, false, false), 3.04),
        new("ain",         "Ain",                      "epTau",      [],                                    new(false, false, false), 3.54),
        new("segin",       "Segin",                    "epCas",      [],                                    new(false, false, false), 3.342),
        new("alpheratz",   "Alpheratz",                "alAnd",      ["Sirrah"],                            new(true,  true,  true), 2.06),
        new("mirach",      "Mirach",                   "beAnd",      [],                                    new(false, true,  true), 2.06),
        new("almaak",      "Almaak",                   "ga-1And",    ["Almak", "Almac", "Almach"],          new(false, true,  false), 2.26),
        new("adhil",       "Adhil",                    "xiAnd",      [],                                    new(false, false, false), 4.875),
        new("adhab",       "Adhab",                    "upAnd",      [],                                    new(false, false, false), 4.09),
        new("altair",      "Altair",                   "alAql",      [],                                    new(true,  true,  true), 0.77),
        new("alshain",     "Alshain",                  "beAql",      [],                                    new(false, false, false), 3.71),
        new("tarazed",     "Tarazed",                  "gaAql",      [],                                    new(false, false, false), 2.724),
        new("alMizan",     "Al Mizan",                 "deAql",      [],                                    new(false, false, false), 3.4),
        new("denebElOkabBorealis",   "Deneb el Okab Borealis",  "epAql",  [],                              new(false, false, false), 4.025),
        new("denebElOkabAustralis",  "Deneb el Okab Australis", "zeAql",  ["Dheneb"],                      new(false, false, false), 2.988),
        new("bazak",       "Bazak",                    "etAql",      [],                                    new(false, false, false), 3.88),
        new("tseenFoo",    "Tseen Foo",                "thAql",      [],                                    new(false, false, false), 3.242),
        new("alThalimaimPosterior",  "Al Thalimaim Posterior",  "ioAql",  [],                              new(false, false, false), 4.349),
        new("alThalimaimAnterior",   "Al Thalimaim Anterior",   "laAql",  [],                              new(false, false, false), 3.427),
        new("bered",       "Bered",                    "12Aql",      [],                                    new(false, false, false), 4.027),
        new("sadalmelek",  "Sadalmelek",               "alAqr",      ["Sadalmelik"],                        new(false, true,  true), 2.95),
        new("sadalsuud",   "Sadalsuud",                "beAqr",      [],                                    new(false, true,  true), 2.91),
        new("sadalachbia", "Sadalachbia",              "gaAqr",      [],                                    new(false, false, false), 3.847),
        new("skat",        "Skat",                     "deAqr",      [],                                    new(false, true,  false), 3.269),
        new("albali",      "Albali",                   "epAqr",      ["Altager"],                           new(false, false, false), 3.77),
        new("sadaltager",  "Sadaltager",               "ze-1Aqr",    [],                                    new(false, false, false), 4.5),
        new("hydria",      "Hydria",                   "etAqr",      ["Deli"],                              new(false, false, false), 4.03),
        new("ancha",       "Ancha",                    "thAqr",      [],                                    new(false, false, false), 4.175),
        new("situla",      "Situla",                   "kaAqr",      [],                                    new(false, false, false), 5.04),
        new("hydor",       "Hydor",                    "laAqr",      ["Ekkhysis"],                          new(false, false, false), 3.766),
        new("albulaan",    "Albulaan",                 "nuAqr",      [],                                    new(false, false, false), 4.519),
        new("seat",        "Seat",                     "piAqr",      [],                                    new(false, false, false), 4.794),
        new("bunda",       "Bunda",                    "xiAqr",      [],                                    new(false, false, false), 4.69),
        new("ara",         "Ara",                      "alAra",      [],                                    new(false, false, false), 2.836),
        new("hamal",       "Hamal",                    "alAri",      [],                                    new(false, true,  true), 2),
        new("sheratan",    "Sheratan",                 "beAri",      [],                                    new(false, true,  false), 2.64),
        new("mesarthim",   "Mesarthim",                "gaAri",      [],                                    new(false, false, false), 3.88),
        new("botein",      "Botein",                   "deAri",      [],                                    new(false, false, false), 4.35),
        new("capella",     "Capella",                  "alAur",      [],                                    new(true,  true,  true), 0.08),
        new("menkalinan",  "Menkalinan",               "beAur",      [],                                    new(true,  true,  false), 1.896),
        new("prijipati",   "Prijipati",                "deAur",      [],                                    new(false, false, false), 3.72),
        new("maaz",        "Maaz",                     "epAur",      ["Al Anz"],                            new(false, false, false), 3.039),
        new("haedi",       "Haedi",                    "zeAur",      ["Haedus", "Hoedus I", "Sadatoni"],    new(false, false, false), 3.769),
        new("hoedusIi",    "Hoedus II",                "etAur",      [],                                    new(false, false, false), 3.158),
        new("bogardus",    "Bogardus",                 "thAur",      ["Manus"],                             new(false, false, false), 2.62),
        new("hasseleh",    "Hasseleh",                 "ioAur",      ["Al Khabdhilinan"],                   new(false, false, false), 2.693),
        new("arcturus",    "Arcturus",                 "alBoo",      [],                                    new(true,  true,  true), -0.04),
        new("nekkar",      "Nekkar",                   "beBoo",      [],                                    new(false, false, false), 3.488),
        new("seginus",     "Seginus",                  "gaBoo",      ["Haris"],                             new(false, true,  false), 3),
        new("princeps",    "Princeps",                 "deBoo",      [],                                    new(false, true,  false), 3.47),
        new("izar",        "Izar",                     "epBoo",      ["Mirak", "Pulcherrima"],              new(false, false, false), 2.39),
        new("mufrid",      "Mufrid",                   "etBoo",      ["Muphrid"],                           new(false, false, false), 2.68),
        new("asellusPrimus",   "Asellus Primus",       "thBoo",      [],                                    new(false, false, false), 4.1),
        new("asellusSecundus", "Asellus Secundus",     "ioBoo",      [],                                    new(false, false, false), 4.75),
        new("asellusTertius",  "Asellus Tertius",      "ka-2Boo",    [],                                    new(false, false, false), 4.5),
        new("alkalurops",  "Alkalurops",               "mu-1Boo",    [],                                    new(false, false, false), 4.307),
        new("hemeleinPrima",   "Hemelein Prima",       "rhBoo",      ["Al Hamalain"],                       new(false, false, false), 3.583),
        new("hemeleinSecunda", "Hemelein Secunda",     "siBoo",      [],                                    new(false, false, false), 4.46),
        new("ceginus",     "Ceginus",                  "phBoo",      [],                                    new(false, false, false), 5.263),
        new("merga",       "Merga",                    "38Boo",      [],                                    new(false, false, false), 5.769),
        new("algedi1",     "Algedi",                   "al-1Cap",    ["Giedi Prima"],                       new(false, true,  false), 4.249),
        new("algedi2",     "Algedi",                   "al-2Cap",    ["Giedi Secunda"],                     new(false, false, false), 3.585),
        new("dabih",       "Dabih",                    "beCap",      [],                                    new(false, true,  false), 3.08),
        new("nashira",     "Nashira",                  "gaCap",      [],                                    new(false, true,  false), 3.68),
        new("denebAlgedi", "Deneb Algedi",             "deCap",      [],                                    new(false, true,  true), 2.87),
        new("castra",      "Castra",                   "epCap",      [],                                    new(false, true,  false), 4.5),
        new("marakk",      "Marakk",                   "zeCap",      [],                                    new(false, false, false), 3.754),
        new("armus",       "Armus",                    "etCap",      [],                                    new(false, true,  false), 4.856),
        new("dorsum",      "Dorsum",                   "thCap",      [],                                    new(false, true,  false), 4.073),
        new("alshat",      "Alshat",                   "nuCap",      [],                                    new(false, false, false), 4.754),
        new("oculus",      "Oculus",                   "piCap",      [],                                    new(false, true,  false), 5.25),
        new("bos",         "Bos",                      "rhCap",      [],                                    new(false, true,  false), 4.803),
        new("pazan",       "Pazan",                    "psCap",      ["Pazhan"],                            new(false, false, false), 4.152),
        new("batenAlgiedi","Baten Algiedi",            "omeCap",     [],                                    new(false, false, false), 4.124),
        new("canopus",     "Canopus",                  "alCar",      [],                                    new(true,  true,  true), -0.72),
        new("miaplacidus", "Miaplacidus",              "beCar",      [],                                    new(false, false, false), 1.7),
        new("avior",       "Avior",                    "epCar",      [],                                    new(false, false, false), 1.953),
        new("foramen",     "Foramen",                  "etCar",      [],                                    new(false, true,  false), 8.13),
        new("vathorzPosterior","Vathorz Posterior",    "thCar",      [],                                    new(false, false, false), 2.78),
        new("scutulum",    "Scutulum",                 "ioCar",      ["Tureis", "Aspidiske"],               new(false, false, false), 2.249),
        new("drus",        "Drus",                     "chCar",      ["Drys"],                              new(false, false, false), 3.444),
        new("simiram",     "Simiram",                  "omeCar",     [],                                    new(false, false, false), 3.3),
        new("vathorzPrior","Vathorz Prior",            "upCar",      [],                                    new(false, false, false), 2.96),
        new("schedar",     "Schedar",                  "alCas",      ["Shedir", "Schedir"],                 new(false, false, true), 2.252),
        new("caph",        "Caph",                     "beCas",      [],                                    new(false, false, false), 2.27),
        new("tsih",        "Tsih",                     "gaCas",      ["Cih"],                               new(false, false, false), 2.47),
        new("ruchbah",     "Ruchbah",                  "deCas",      ["Rucha"],                             new(false, false, false), 2.68),
        new("achird",      "Achird",                   "etCas",      [],                                    new(false, false, false), 3.45),
        new("marfak",      "Marfak",                   "muCas",      [],                                    new(false, false, false), 5.12),
        new("rigilKent",   "Rigil Kent",               "alCen",      ["Rigel Kentaurus","Toliman","Bungula"],new(false, true,  true), -0.1),
        new("hadar",       "Hadar",                    "beCen",      ["Agena"],                             new(false, true,  true), 0.6),
        new("muhlifain",   "Muhlifain",                "gaCen",      [],                                    new(false, false, false), 2.18),
        new("birdun",      "Birdun",                   "epCen",      [],                                    new(false, false, false), 2.265),
        new("menkent",     "Menkent",                  "thCen",      [],                                    new(false, false, false), 2.06),
        new("alhakim",     "Alhakim",                  "ioCen",      [],                                    new(false, false, false), 2.7),
        new("keKwan",      "Ke Kwan",                  "kaCen",      [],                                    new(false, false, false), 3.13),
        new("maTi",        "Ma Ti",                    "laCen",      ["Mati"],                              new(false, false, false), 3.117),
        new("kabkentSecunda",  "Kabkent Secunda",      "nuCen",      [],                                    new(false, false, false), 3.39),
        new("kabkentTertia",   "Kabkent Tertia",       "phCen",      [],                                    new(false, false, false), 3.806),
        new("proximaCentauri", "Proxima Centauri",     "V645 Cen",   [],                                    new(false, false, false), 11.05),
        new("alderamin",   "Alderamin",                "alCep",      [],                                    new(false, false, true), 2.46),
        new("alphirk",     "Alphirk",                  "beCep",      ["Alfirk"],                            new(false, false, false), 3.216),
        new("alrai",       "Alrai",                    "gaCep",      ["Errai"],                             new(false, false, false), 3.22),
        new("alradif",     "Alradif",                  "deCep",      ["Alredif"],                           new(false, false, false), 4.07),
        new("phicares",    "Phicares",                 "epCep",      ["Phicareus"],                         new(false, false, false), 4.19),
        new("kurhah",      "Kurhah",                   "zeCep",      [],                                    new(false, false, false), 3.359),
        new("alagemin",    "Alagemin",                 "etCep",      [],                                    new(false, false, false), 3.41),
        new("alkidr",      "Alkidr",                   "thCep",      [],                                    new(false, false, false), 4.22),
        new("alvahet",     "Alvahet",                  "ioCep",      [],                                    new(false, false, false), 3.51),
        new("erakis",      "Erakis",                   "muCep",      ["The Garnet Star"],                   new(false, false, false), 4.04),
        new("kurdah",      "Kurdah",                   "xiCep",      ["Alkurhah"],                          new(false, false, false), 6.5),
        new("alKalbAlRai", "Al Kalb al Rai",           "rhCep",      [],                                    new(false, false, false), 5.46),
        new("menkar1",     "Menkar",                   "alCet",      [],                                    new(false, true,  true), 2.514),
        new("diphda",      "Diphda",                   "beCet",      ["Difda"],                             new(false, true,  false), 2.04),
        new("kaffaljidhma","Kaffaljidhma",             "gaCet",      [],                                    new(false, false, false), 3.47),
        new("phycochroma", "Phycochroma",              "deCet",      [],                                    new(false, false, false), 4.07),
        new("batenKaitos",  "Baten Kaitos",            "zeCet",      [],                                    new(false, true,  false), 3.738),
        new("denebAlgenubi","Deneb Algenubi",          "etCet",      [],                                    new(false, true,  false), 3.45),
        new("altawk",      "Altawk",                   "thCet",      [],                                    new(false, false, false), 3.6),
        new("denebKaitos", "Deneb Kaitos",             "ioCet",      ["Shemali"],                           new(false, false, false), 3.558),
        new("menkar2",     "Menkar",                   "laCet",      [],                                    new(false, false, false), 4.701),
        new("alSadrAlKetus","Al Sadr al Ketus",        "piCet",      [],                                    new(false, false, false), 4.235),
        new("abyssusAqueus","Abyssus Aqueus",          "upCet",      [],                                    new(false, false, false), 4.015),
        new("alNitham",    "Al Nitham",                "ph-1Cet",    [],                                    new(false, false, false), 4.775),
        new("mirzam",      "Mirzam",                   "beCMa",      ["Murzim","Murzims"],                  new(false, false, true), 2),
        new("muliphein",   "Muliphein",                "gaCMa",      ["Isis"],                              new(false, false, false), 4.097),
        new("wezen",       "Wezen",                    "deCMa",      [],                                    new(false, false, false), 1.842),
        new("adara",       "Adara",                    "epCMa",      ["Adhara"],                            new(false, false, false), 1.513),
        new("furud",       "Furud",                    "zeCMa",      [],                                    new(false, false, false), 3),
        new("aludra",      "Aludra",                   "etCMa",      [],                                    new(false, false, false), 2.4),
        new("procyon",     "Procyon",                  "alCMi",      [],                                    new(true,  true,  true), 0.34),
        new("gomeisa",     "Gomeisa",                  "beCMi",      [],                                    new(false, false, false), 2.886),
        new("acubens",     "Acubens",                  "alCnc",      [],                                    new(false, true,  true), 4.259),
        new("alTarf",      "Al Tarf",                  "beCnc",      [],                                    new(false, false, false), 3.52),
        new("asellusBorealis", "Asellus Borealis",     "gaCnc",      [],                                    new(false, true,  false), 4.668),
        new("asellusAustralis","Asellus Australis",    "deCnc",      [],                                    new(false, true,  false), 3.94),
        new("tegmen",      "Tegmen",                   "zeCnc",      ["Tegmine"],                           new(false, false, false), 5.05),
        new("decapoda",    "Decapoda",                 "ioCnc",      [],                                    new(false, false, false), 4.028),
        new("phact",       "Phact",                    "alCol",      [],                                    new(false, true,  true), 2.6),
        new("wazn",        "Wazn",                     "beCol",      [],                                    new(false, false, false), 3.12),
        new("ghusnAlZaitun","Ghusn al Zaitun",         "deCol",      [],                                    new(false, false, false), 3.853),
        new("alKurud",     "Al Kurud",                 "kaCol",      [],                                    new(false, false, false), 4.374),
        new("tsze",        "Tsze",                     "laCol",      [],                                    new(false, false, false), 4.863),
        new("diadem",      "Diadem",                   "alCom",      [],                                    new(false, false, true), 4.32),
        new("aldafirah",   "Aldafirah",                "beCom",      [],                                    new(false, false, false), 4.26),
        new("kissin",      "Kissin",                   "gaCom",      [],                                    new(false, false, false), 4.35),
        new("alphecca",    "Alphecca",                 "alCrB",      ["Alphekka","Gemma"],                  new(true,  true,  true), 2.214),
        new("nusakan",     "Nusakan",                  "beCrB",      [],                                    new(false, false, false), 3.68),
        new("theBlazeStar","The Blaze Star",           "taCrB",      [],                                    new(false, false, false), 4.76),
        new("alfeccaMeridiana","Alfecca Meridiana",    "alCrA",      [],                                    new(false, false, false), 4.102),
        new("alkes",       "Alkes",                    "alCrt",      [],                                    new(false, false, true), 4.07),
        new("alsharasif",  "Alsharasif",               "beCrt",      [],                                    new(false, false, false), 4.461),
        new("labrum",      "Labrum",                   "deCrt",      [],                                    new(false, true,  false), 3.56),
        new("acrux",       "Acrux",                    "alCru",      [],                                    new(false, true,  true), 0.81),
        new("mimosa",      "Mimosa",                   "beCru",      [],                                    new(false, false, false), 1.297),
        new("gacrux",      "Gacrux",                   "gaCru",      [],                                    new(false, false, false), 1.63),
        new("decrux",      "Decrux",                   "deCru",      [],                                    new(false, false, false), 2.775),
        new("juxtaCrucem", "Juxta Crucem",             "epCru",      [],                                    new(false, false, false), 3.59),
        new("alchiba",     "Alchiba",                  "alCrv",      ["Alchita"],                           new(false, false, false), 4),
        new("kraz",        "Kraz",                     "beCrv",      [],                                    new(false, false, false), 2.65),
        new("gienahCorvi", "Gienah Corvi",             "gaCrv",      [],                                    new(false, false, false), 2.59),
        new("algorab",     "Algorab",                  "deCrv",      [],                                    new(false, true,  false), 2.95),
        new("minkar",      "Minkar",                   "epCrv",      [],                                    new(false, false, false), 3.017),
        new("avisSatyra",  "Avis Satyra",              "etCrv",      [],                                    new(false, false, false), 4.31),
        new("corCaroli",   "Cor Caroli",               "al-2CVn",    [],                                    new(false, false, false), 2.9),
        new("asterion",    "Asterion",                 "beCVn",      ["Chara"],                             new(false, false, false), 4.26),
        new("albireo",     "Albireo",                  "be-1Cyg",    [],                                    new(false, true,  false), 3.085),
        new("sador",       "Sador",                    "gaCyg",      ["Sadir","Sadr"],                      new(false, false, false), 2.237),
        new("ruc",         "Ruc",                      "deCyg",      ["Rukh","Urakhga","Al Fawaris"],       new(false, false, false), 2.9),
        new("gienahCygni", "Gienah Cygni",             "epCyg",      ["Gienah Ghurab"],                    new(false, false, false), 2.48),
        new("azelfafage",  "Azelfafage",               "pi-1Cyg",    [],                                    new(false, false, false), 4.66),
        new("ruchbahI",    "Ruchbah I",                "ome-1Cyg",   [],                                    new(false, false, false), 4.938),
        new("ruchbahIi",   "Ruchbah II",               "ome-2Cyg",   [],                                    new(false, false, false), 5.468),
        new("sualocin",    "Sualocin",                 "alDel",      [],                                    new(false, false, true), 3.8),
        new("rotanev",     "Rotanev",                  "beDel",      [],                                    new(false, false, false), 3.632),
        new("denebDulphim","Deneb Dulphim",            "epDel",      [],                                    new(false, false, false), 4.032),
        new("thuban",      "Thuban",                   "alDra",      [],                                    new(false, false, true), 3.68),
        new("alwaid",      "Alwaid",                   "beDra",      ["Rastaban"],                          new(false, true,  false), 2.79),
        new("eltanin",     "Eltanin",                  "gaDra",      ["Etamin"],                            new(false, false, false), 2.23),
        new("nodusIi",     "Nodus II",                 "deDra",      ["Altais"],                            new(false, false, false), 3.082),
        new("tyl",         "Tyl",                      "epDra",      [],                                    new(false, false, false), 3.83),
        new("nodusI",      "Nodus I",                  "zeDra",      ["Aldhibah"],                          new(false, false, false), 3.174),
        new("alsafi1",     "Alsafi",                   "thDra",      [],                                    new(false, false, false), 4),
        new("edasich",     "Edasich",                  "ioDra",      ["Ed Asich"],                          new(false, false, false), 3.31),
        new("ketu",        "Ketu",                     "kaDra",      [],                                    new(false, false, false), 3.881),
        new("giansar",     "Giansar",                  "laDra",      ["Gianfar"],                           new(false, false, false), 3.828),
        new("arrakis",     "Arrakis",                  "muDra",      [],                                    new(false, false, false), 4.92),
        new("kuma1",       "Kuma",                     "nu-1Dra",    [],                                    new(false, false, false), 4.888),
        new("kuma2",       "Kuma",                     "nu-2Dra",    [],                                    new(false, false, false), 4.865),
        new("grumium",     "Grumium",                  "xiDra",      [],                                    new(false, false, false), 3.741),
        new("alsafi2",     "Alsafi",                   "siDra",      ["Athafi"],                            new(false, false, false), 4.68),
        new("batentabanBorealis",  "Batentaban Borealis",  "chDra",  [],                                    new(false, false, false), 3.58),
        new("dziban",      "Dziban",                   "ps-1Dra",    [],                                    new(false, false, false), 4.56),
        new("alathfar1",   "Alathfar",                 "omeDra",     ["Al Athfar"],                         new(false, false, false), 4.8),
        new("aldhibain",   "Aldhibain",                "etDra",      [],                                    new(false, false, false), 2.736),
        new("batentabanAustralis", "Batentaban Australis","phDra",   [],                                    new(false, false, false), 4.22),
        new("kitalpha",    "Kitalpha",                 "alEqu",      [],                                    new(false, false, false), 3.949),
        new("achernar",    "Achernar",                 "alEri",      [],                                    new(true,  true,  true), 0.5),
        new("cursa",       "Cursa",                    "beEri",      [],                                    new(false, false, false), 2.79),
        new("zaurak",      "Zaurak",                   "gaEri",      [],                                    new(false, false, false), 2.978),
        new("rana",        "Rana",                     "deEri",      [],                                    new(false, false, false), 3.51),
        new("azha",        "Azha",                     "etEri",      [],                                    new(false, false, false), 3.89),
        new("acamar",      "Acamar",                   "th-1Eri",    [],                                    new(false, false, false), 3.2),
        new("zibal",       "Zibal",                    "zeEri",      [],                                    new(false, false, false), 4.792),
        new("beid",        "Beid",                     "omi-1Eri",   [],                                    new(false, false, false), 4.04),
        new("keid",        "Keid",                     "omi-2Eri",   [],                                    new(false, false, false), 4.41),
        new("angetenar",   "Angetenar",                "ta-2Eri",    [],                                    new(false, false, false), 4.75),
        new("theemin",     "Theemin",                  "up-2Eri",    [],                                    new(false, false, false), 3.817),
        new("sceptrum",    "Sceptrum",                 "53Eri",      [],                                    new(false, false, false), 3.85),
        new("fornacis",    "Fornacis",                 "alFor",      [],                                    new(false, false, false), 3.85),
        new("castor",      "Castor",                   "alGem",      [],                                    new(true,  true,  true), 1.59),
        new("pollux",      "Pollux",                   "beGem",      [],                                    new(true,  true,  true), 1.15),
        new("alhena",      "Alhena",                   "gaGem",      ["Almeisan"],                          new(false, true,  true), 1.9),
        new("wasat",       "Wasat",                    "deGem",      [],                                    new(false, true,  false), 3.53),
        new("mebsuta",     "Mebsuta",                  "epGem",      [],                                    new(false, false, false), 3.019),
        new("mekbuda",     "Mekbuda",                  "zeGem",      [],                                    new(false, false, false), 4.01),
        new("propusEtagem","Propus etaGem",            "etGem",      [],                                    new(false, true,  false), 3.32),
        new("nageba",      "Nageba",                   "thGem",      [],                                    new(false, false, false), 3.6),
        new("propusIotgem","Propus iotGem",            "ioGem",      [],                                    new(false, true,  false), 3.793),
        new("alKrikab",    "Al Krikab",                "kaGem",      [],                                    new(false, false, false), 3.57),
        new("kebash",      "Kebash",                   "laGem",      ["Alkibash"],                          new(false, false, false), 3.581),
        new("tejat",       "Tejat",                    "muGem",      [],                                    new(false, true,  false), 2.914),
        new("alzirr",      "Alzirr",                   "xiGem",      [],                                    new(false, false, false), 3.4),
        new("alnair",      "Alnair",                   "alGru",      [],                                    new(false, false, false), 1.74),
        new("gruid",       "Gruid",                    "beGru",      [],                                    new(false, false, false), 2.13),
        new("alDhanab",    "Al Dhanab",                "gaGru",      ["Ras Alkurki"],                       new(false, false, false), 3.01),
        new("rasAlgethi",  "Ras Algethi",              "alHer",      ["Rasalgethi"],                        new(false, false, true), 3.06),
        new("kornephoros", "Kornephoros",              "beHer",      [],                                    new(false, false, false), 2.786),
        new("rutilicus",   "Rutilicus",                "zeHer",      [],                                    new(false, false, false), 2.8),
        new("sarin",       "Sarin",                    "deHer",      [],                                    new(false, false, false), 3.126),
        new("kajamEpsher", "Kajam epsHer",             "epHer",      [],                                    new(false, false, false), 3.906),
        new("sofian",      "Sofian",                   "etHer",      [],                                    new(false, false, false), 3.487),
        new("rukbalgethiGenubi", "Rukbalgethi Genubi", "thHer",      [],                                    new(false, false, false), 3.851),
        new("alJathiyah",  "Al Jathiyah",              "ioHer",      [],                                    new(false, false, false), 3.8),
        new("marsik",      "Marsik",                   "kaHer",      ["Marfik"],                            new(false, false, false), 5),
        new("masym",       "Masym",                    "laHer",      ["Maasym"],                            new(false, false, false), 4.402),
        new("melkarth",    "Melkarth",                 "muHer",      [],                                    new(false, false, false), 3.417),
        new("fudail",      "Fudail",                   "piHer",      [],                                    new(false, false, false), 3.156),
        new("rukbalgethiShemali","Rukbalgethi Shemali","taHer",      [],                                    new(false, false, false), 3.9),
        new("kajamOmeher", "Kajam omeHer",             "omeHer",     ["Cujam"],                             new(false, false, false), 4.574),
        new("apex",        "Apex",                     "HerA*",      [],                                    new(false, false, false), 999.99),
        new("alphard",     "Alphard",                  "alHya",      ["Cor Hydrae"],                        new(true,  true,  true), 2.004),
        new("caudaHydrae", "Cauda Hydrae",             "gaHya",      ["Dhanab al Shuja"],                   new(false, false, false), 3),
        new("mautinah",    "Mautinah",                 "deHya",      [],                                    new(false, false, false), 4.137),
        new("ashlesha",    "Ashlesha",                 "epHya",      [],                                    new(false, false, false), 3.38),
        new("hydrobius",   "Hydrobius",                "zeHya",      [],                                    new(false, false, false), 3.127),
        new("pleura",      "Pleura",                   "nuHya",      [],                                    new(false, false, false), 3.11),
        new("sataghni",    "Sataghni",                 "piHya",      [],                                    new(false, false, false), 3.263),
        new("alMinliarAlShuja","Al Minliar al Shuja",  "siHya",      ["Minchir"],                           new(false, false, false), 4.452),
        new("ukdah1",      "Ukdah",                    "ta-1Hya",    [],                                    new(false, false, false), 4.6),
        new("ukdah2",      "Ukdah",                    "ta-2Hya",    [],                                    new(false, false, false), 4.555),
        new("denebola",    "Denebola",                 "beLeo",      [],                                    new(true,  true,  true), 2.14),
        new("algieba1",    "Algieba",                  "ga-1Leo",    [],                                    new(false, false, false), 2.12),
        new("dhur",        "Dhur",                     "deLeo",      ["Zosma"],                             new(false, true,  true), 2.56),
        new("rasElasedAustralis","Ras Elased Australis","epLeo",     [],                                    new(false, false, false), 2.975),
        new("adhafera",    "Adhafera",                 "zeLeo",      [],                                    new(false, true,  false), 3.443),
        new("algieba2",    "Algieba",                  "etLeo",      ["Al Jabhah"],                         new(false, false, false), 3.511),
        new("tseTseng",    "Tse Tseng",                "ioLeo",      ["Tsze Tseang"],                       new(false, false, false), 4),
        new("alminhar",    "Alminhar",                 "kaLeo",      ["Al Minliar al Asad"],                new(false, false, false), 4.473),
        new("alterf",      "Alterf",                   "laLeo",      [],                                    new(false, false, false), 4.317),
        new("rasElasedBorealis","Ras Elased Borealis", "muLeo",      ["Rasalas"],                           new(false, false, false), 3.88),
        new("subra",       "Subra",                    "omiLeo",     [],                                    new(false, false, false), 3.531),
        new("shishimai",   "Shishimai",                "siLeo",      [],                                    new(false, false, false), 4.044),
        new("coxa",        "Coxa",                     "thLeo",      ["Chertan","Cestan","Chort"],           new(false, false, false), 3.324),
        new("shir",        "Shir",                     "rhLeo",      [],                                    new(false, false, false), 3.87),
        new("arneb",       "Arneb",                    "alLep",      [],                                    new(false, false, false), 2.597),
        new("nihal",       "Nihal",                    "beLep",      [],                                    new(false, false, false), 2.84),
        new("sasin",       "Sasin",                    "epLep",      [],                                    new(false, false, false), 3.192),
        new("zubenelgenubi","Zubenelgenubi",           "al-2Lib",    ["Zuben Elgenubi"],                    new(true,  true,  true), 2.753),
        new("zubeneshamali","Zubeneshamali",           "beLib",      ["Zuben Eschamali"],                   new(true,  true,  true), 2.605),
        new("zubenelakrab", "Zubenelakrab",            "gaLib",      ["Zuben Elakrab"],                     new(false, false, false), 3.925),
        new("zubenelakribi","Zubenelakribi",           "deLib",      ["Zuben Elakribi"],                    new(false, false, false), 4.95),
        new("zubenhakrabi", "Zubenhakrabi",            "nuLib",      ["Zuben Hakrabi"],                     new(false, false, false), 5.202),
        new("brachium",    "Brachium",                 "siLib",      [],                                    new(false, false, false), 3.3),
        new("praecipua",   "Praecipua",                "46 LMi",     [],                                    new(false, false, false), 3.83),
        new("kakkab",      "Kakkab",                   "alLup",      ["Men"],                               new(false, false, false), 2.276),
        new("kekouan",     "Kekouan",                  "beLup",      [],                                    new(false, false, false), 2.665),
        new("thusia",      "Thusia",                   "gaLup",      [],                                    new(false, false, false), 2.765),
        new("hilasmus",    "Hilasmus",                 "deLup",      [],                                    new(false, false, false), 3.203),
        new("alvashak",    "Alvashak",                 "alLyn",      ["Al Fahd"],                           new(false, false, false), 3.16),
        new("alsciaukat",  "Alsciaukat",               "31Lyn",      ["Mabsuthat"],                         new(false, false, false), 4.258),
        new("mabsuthat",   "Mabsuthat",                "kaLyn",      [],                                    new(false, false, false), 4.258),
        new("maculosa",    "Maculosa",                 "38Lyn",      ["Maculata"],                          new(false, false, false), 3.82),
        new("vega",        "Vega",                     "alLyr",      [],                                    new(true,  true,  true), 0.03),
        new("sheliak",     "Sheliak",                  "beLyr",      [],                                    new(false, false, false), 3.52),
        new("sulaphat",    "Sulaphat",                 "gaLyr",      ["Sulafat"],                           new(false, false, false), 3.25),
        new("aladfar",     "Aladfar",                  "etLyr",      [],                                    new(false, false, false), 4.397),
        new("alathfar2",   "Alathfar",                 "muLyr",      [],                                    new(false, false, false), 5.12),
        new("polarisAustralis","Polaris Australis",    "siOct",      [],                                    new(false, false, false), 5.42),
        new("rasalhague",  "Rasalhague",               "alOph",      [],                                    new(false, true,  true), 2.1),
        new("celbalrai",   "Celbalrai",                "beOph",      ["Kelb Alrai"],                        new(false, false, false), 2.75),
        new("alDurajah",   "Al Durajah",               "gaOph",      [],                                    new(false, false, false), 3.75),
        new("yedPrior",    "Yed Prior",                "deOph",      [],                                    new(false, true,  false), 2.74),
        new("yedPosterior","Yed Posterior",            "epOph",      [],                                    new(false, false, false), 3.24),
        new("han",         "Han",                      "zeOph",      [],                                    new(false, true,  false), 2.578),
        new("sabik",       "Sabik",                    "etOph",      [],                                    new(false, true,  false), 2.43),
        new("imad",        "Imad",                     "thOph",      [],                                    new(false, false, false), 3.248),
        new("helkath",     "Helkath",                  "kaOph",      [],                                    new(false, false, false), 3.2),
        new("marfik",      "Marfik",                   "laOph",      [],                                    new(false, false, false), 3.9),
        new("sinistra",    "Sinistra",                 "nuOph",      [],                                    new(false, true,  false), 3.309),
        new("barnardsStar","Barnard's star",           "V2500 Oph",  [],                                    new(false, false, false), 9.511),
        new("betelgeuse",  "Betelgeuse",               "alOri",      ["Beteigeuse"],                        new(true,  true,  true), 0.42),
        new("bellatrix",   "Bellatrix",                "gaOri",      [],                                    new(true,  true,  true), 1.64),
        new("mintaka",     "Mintaka",                  "deOri",      [],                                    new(false, true,  false), 2.23),
        new("alnilam",     "Alnilam",                  "epOri",      [],                                    new(true,  true,  true), 1.7),
        new("alnitak",     "Alnitak",                  "zeOri",      [],                                    new(false, false, false), 1.79),
        new("trapezium",   "Trapezium",                "th-1COri",   [],                                    new(false, false, false), 5.13),
        new("hatsya",      "Hatsya",                   "ioOri",      ["Nair al Saif"],                      new(false, false, false), 2.77),
        new("saiph",       "Saiph",                    "kaOri",      [],                                    new(false, false, false), 2.049),
        new("heka",        "Heka",                     "laOri",      ["Meissa"],                            new(false, false, false), 3.39),
        new("tabit1",      "Tabit",                    "pi-3Ori",    [],                                    new(false, false, false), 3.19),
        new("tabit2",      "Tabit",                    "pi-4Ori",    [],                                    new(false, false, false), 3.68),
        new("thabit",      "Thabit",                   "upOri",      [],                                    new(false, false, false), 4.62),
        new("peacock",     "Peacock",                  "alPav",      [],                                    new(false, false, false), 1.91),
        new("ankaa",       "Ankaa",                    "alPhe",      [],                                    new(false, false, true), 2.37),
        new("markab",      "Markab",                   "alPeg",      [],                                    new(false, true,  true), 2.49),
        new("scheat",      "Scheat",                   "bePeg",      [],                                    new(false, true,  true), 2.42),
        new("algenib",     "Algenib",                  "gaPeg",      [],                                    new(false, true,  false), 2.83),
        new("enif",        "Enif",                     "epPeg",      [],                                    new(false, false, false), 2.404),
        new("homam",       "Homam",                    "zePeg",      [],                                    new(false, false, false), 3.4),
        new("matar",       "Matar",                    "etPeg",      [],                                    new(false, false, false), 2.948),
        new("biham",       "Biham",                    "thPeg",      ["Baham"],                             new(false, false, false), 3.5),
        new("jih",         "Jih",                      "kaPeg",      [],                                    new(false, false, false), 4.159),
        new("sadalbari",   "Sadalbari",                "laPeg",      [],                                    new(false, false, false), 3.961),
        new("kerb",        "Kerb",                     "taPeg",      ["Salm"],                              new(false, false, false), 4.592),
        new("mirfak",      "Mirfak",                   "alPer",      ["Mirphak"],                           new(false, false, true), 1.816),
        new("atik",        "Atik",                     "zePer",      [],                                    new(false, false, false), 2.883),
        new("miram",       "Miram",                    "etPer",      [],                                    new(false, false, false), 3.774),
        new("misam",       "Misam",                    "kaPer",      [],                                    new(false, false, false), 3.8),
        new("menkib",      "Menkib",                   "xiPer",      [],                                    new(false, false, false), 4.06),
        new("atiks",       "Atiks",                    "omiPer",     [],                                    new(false, false, false), 3.855),
        new("gorgonaSecunda","Gorgona Secunda",         "piPer",     [],                                    new(false, false, false), 4.685),
        new("gorgonaTertia","Gorgona Tertia",          "rhPer",      [],                                    new(false, false, false), 3.42),
        new("gorgonaQuatra","Gorgona Quatra",          "omePer",     [],                                    new(false, false, false), 3.7),
        new("capulus1",    "Capulus",                  "NGC869",     [],                                    new(false, true,  true), 3.7),
        new("capulus2",    "Capulus",                  "M34",        [],                                    new(false, false, false), 5.2),
        new("fomalhaut",   "Fomalhaut",                "alPsA",      [],                                    new(true,  true,  true), 1.16),
        new("tienKang",    "Tien Kang",                "bePsA",      [],                                    new(false, false, false), 4.289),
        new("aboras",      "Aboras",                   "dePsA",      [],                                    new(false, false, false), 4.226),
        new("alrischa",    "Alrischa",                 "alPsc",      ["Al Rescha"],                         new(false, false, true), 3.82),
        new("fumAlsamakah","Fum Alsamakah",            "bePsc",      ["Samakah"],                           new(false, false, false), 4.486),
        new("simmah",      "Simmah",                   "gaPsc",      [],                                    new(false, false, false), 3.69),
        new("linteum",     "Linteum",                  "dePsc",      [],                                    new(false, false, false), 4.439),
        new("kaht",        "Kaht",                     "epPsc",      [],                                    new(false, false, false), 4.28),
        new("alPherg",     "Al Pherg",                 "etPsc",      [],                                    new(false, true,  false), 3.62),
        new("torcularisSeptentrionalis","Torcularis Septentrionalis","omiPsc",[],                           new(false, false, false), 4.272),
        new("anunitum",    "Anunitum",                 "taPsc",      [],                                    new(false, false, false), 4.523),
        new("vernalis",    "Vernalis",                 "omePsc",     [],                                    new(false, false, false), 4.036),
        new("naos",        "Naos",                     "zePup",      ["Suhail Hadar"],                      new(false, false, false), 2.21),
        new("kaimana",     "Kaimana",                  "nuPup",      [],                                    new(false, false, false), 3.171),
        new("azmidiske",   "Azmidiske",                "xiPup",      [],                                    new(false, false, false), 3.337),
        new("ahadi",       "Ahadi",                    "piPup",      [],                                    new(false, false, false), 2.729),
        new("turais",      "Turais",                   "rhPup",      [],                                    new(false, false, false), 2.81),
        new("alRihla",     "Al Rihla",                 "taPup",      ["Rehla","Anazitisi"],                 new(false, false, false), 2.93),
        new("graffias",    "Graffias",                 "be-1Sco",    ["Akrab","Acrab"],                     new(false, true,  false), 4.89),
        new("aculeus",     "Aculeus",                  "M6",         [],                                    new(false, true,  true), 4.2),
        new("acumen",      "Acumen",                   "M7",         [],                                    new(false, true,  true), 3.3),
        new("dschubba",    "Dschubba",                 "deSco",      [],                                    new(false, true,  false), 2.291),
        new("wei",         "Wei",                      "epSco",      [],                                    new(false, false, false), 2.29),
        new("sargas",      "Sargas",                   "thSco",      [],                                    new(false, false, false), 1.862),
        new("girtab",      "Girtab",                   "kaSco",      [],                                    new(false, false, false), 2.375),
        new("shaula",      "Shaula",                   "laSco",      [],                                    new(false, false, false), 1.62),
        new("jabbah",      "Jabbah",                   "nuSco",      [],                                    new(false, true,  false), 4),
        new("grafias",     "Grafias",                  "xiSco",      [],                                    new(false, false, false), 4.17),
        new("alniyat",     "Alniyat",                  "siSco",      [],                                    new(false, false, false), 2.912),
        new("lesath",      "Lesath",                   "upSco",      [],                                    new(false, true,  false), 2.7),
        new("jabhatAlAkrab1","Jabhat al Akrab",        "ome-1Sco",   [],                                    new(false, false, false), 3.946),
        new("jabhatAlAkrab2","Jabhat al Akrab",        "ome-2Sco",   [],                                    new(false, false, false), 4.328),
        new("unukalhai",   "Unukalhai",                "alSer",      ["Cor Serpentis"],                     new(false, true,  false), 2.63),
        new("chow",        "Chow",                     "beSer",      ["Zhou"],                              new(false, false, false), 3.66),
        new("ainalhai",    "Ainalhai",                 "gaSer",      [],                                    new(false, false, false), 3.85),
        new("qin",         "Qin",                      "deSer",      ["Chin"],                              new(false, false, false), 3.79),
        new("nullaPambu",  "Nulla Pambu",              "epSer",      [],                                    new(false, false, false), 3.713),
        new("tang",        "Tang",                     "etSer",      [],                                    new(false, false, false), 3.26),
        new("alya",        "Alya",                     "th-1Ser",    [],                                    new(false, false, false), 4.62),
        new("leiolepis",   "Leiolepis",                "muSer",      ["Leiolepidotus"],                     new(false, false, false), 3.548),
        new("nehushtan",   "Nehushtan",                "xiSer",      [],                                    new(false, false, false), 3.539),
        new("sham",        "Sham",                     "alSge",      [],                                    new(false, false, false), 4.392),
        new("rukbat",      "Rukbat",                   "alSgr",      [],                                    new(true,  false, true), 3.95),
        new("arkabPrior",  "Arkab Prior",              "be-1Sgr",    [],                                    new(false, false, false), 3.954),
        new("arkabPosterior","Arkab Posterior",        "be-2Sgr",    [],                                    new(false, false, false), 4.281),
        new("alnasl",      "Alnasl",                   "ga-2Sgr",    ["Nash"],                              new(false, false, false), 2.99),
        new("kausMedis",   "Kaus Medis",               "deSgr",      ["Kaus Meridionalis"],                 new(false, false, false), 2.71),
        new("kausAustralis","Kaus Australis",          "epSgr",      [],                                    new(false, false, false), 1.8),
        new("ascella",     "Ascella",                  "zeSgr",      [],                                    new(false, true,  false), 2.607),
        new("sephdar",     "Sephdar",                  "etSgr",      ["Ira Furoris"],                       new(false, false, false), 3.11),
        new("kausBorealis","Kaus Borealis",            "laSgr",      [],                                    new(false, false, false), 2.833),
        new("polis",       "Polis",                    "muSgr",      [],                                    new(false, true,  false), 3.841),
        new("ainAlRami",   "Ain al Rami",              "nu-1Sgr",    [],                                    new(false, false, false), 4.859),
        new("manubrium",   "Manubrium",                "omiSgr",     [],                                    new(false, true,  false), 3.771),
        new("albaldah",    "Albaldah",                 "piSgr",      [],                                    new(false, false, false), 2.89),
        new("nunki",       "Nunki",                    "siSgr",      [],                                    new(false, true,  false), 2.058),
        new("hecatebolus", "Hecatebolus",              "taSgr",      [],                                    new(false, false, false), 3.32),
        new("nanto",       "Nanto",                    "phSgr",      [],                                    new(false, false, false), 3.161),
        new("terebellium", "Terebellium",              "omeSgr",     [],                                    new(false, true,  false), 4.7),
        new("facies",      "Facies",                   "M22",        [],                                    new(false, true,  true), 6.17),
        new("spiculum",    "Spiculum",                 "M8",         [],                                    new(false, true,  false), 4.6),
        new("elnath",      "Elnath",                   "beTau",      ["El Nath","Alnath"],                  new(false, true,  true), 1.68),
        new("primaHyadum", "Prima Hyadum",             "gaTau",      ["Hyadum I"],                          new(false, true,  false), 3.654),
        new("secundaHyadum","Secunda Hyadum",          "de-1Tau",    ["Hyadum II"],                         new(false, false, false), 3.764),
        new("alHecka",     "Al Hecka",                 "zeTau",      [],                                    new(false, true,  false), 3.03),
        new("alcyone",     "Alcyone",                  "etTau",      [],                                    new(false, true,  true), 2.873),
        new("phaeo",       "Phaeo",                    "th-1Tau",    [],                                    new(false, false, false), 3.84),
        new("phaesula",    "Phaesula",                 "th-2Tau",    [],                                    new(false, false, false), 3.41),
        new("althaur",     "Althaur",                  "laTau",      [],                                    new(false, false, false), 3.408),
        new("kattupothu",  "Kattupothu",               "muTau",      [],                                    new(false, false, false), 4.28),
        new("furibundus",  "Furibundus",               "nuTau",      [],                                    new(false, false, false), 3.898),
        new("ushakaron",   "Ushakaron",                "xiTau",      [],                                    new(false, false, false), 3.727),
        new("atirsagne",   "Atirsagne",                "omiTau",     [],                                    new(false, false, false), 3.6),
        new("celeano",     "Celeano",                  "16Tau",      [],                                    new(false, false, false), 5.448),
        new("electra",     "Electra",                  "17Tau",      [],                                    new(false, false, false), 3.705),
        new("taygeta",     "Taygeta",                  "19Tau",      [],                                    new(false, false, false), 4.291),
        new("maia",        "Maia",                     "20Tau",      [],                                    new(false, false, false), 3.871),
        new("asterope",    "Asterope",                 "21Tau",      ["Sterope I"],                         new(false, false, false), 5.761),
        new("steropeIi",   "Sterope II",               "22Tau",      [],                                    new(false, false, false), 6.43),
        new("merope",      "Merope",                   "23Tau",      [],                                    new(false, false, false), 4.164),
        new("atlas",       "Atlas",                    "27Tau",      [],                                    new(false, false, false), 3.62),
        new("pleione",     "Pleione",                  "28Tau",      [],                                    new(false, false, false), 5.048),
        new("atria",       "Atria",                    "alTrA",      [],                                    new(false, false, false), 1.92),
        new("rasMutallah", "Ras Mutallah",             "alTri",      ["Metallah"],                          new(false, false, false), 3.41),
        new("dubhe",       "Dubhe",                    "alUMa",      [],                                    new(false, false, true), 1.79),
        new("merak",       "Merak",                    "beUMa",      [],                                    new(false, false, false), 2.346),
        new("phecda",      "Phecda",                   "gaUMa",      [],                                    new(false, false, false), 2.44),
        new("megrez",      "Megrez",                   "deUMa",      [],                                    new(false, false, false), 3.32),
        new("alioth",      "Alioth",                   "epUMa",      [],                                    new(false, false, false), 1.76),
        new("mizar",       "Mizar",                    "zeUMa",      [],                                    new(false, false, false), 2.27),
        new("alkaid",      "Alkaid",                   "etUMa",      ["Benetnash"],                         new(false, false, false), 1.852),
        new("alHaud",      "Al Haud",                  "thUMa",      [],                                    new(false, false, false), 3.2),
        new("talithaBorealis",  "Talitha Borealis",    "ioUMa",      [],                                    new(false, false, false), 3.1),
        new("talithaAustralis", "Talitha Australis",   "kaUMa",      [],                                    new(false, false, false), 3.6),
        new("taniaBorealis",    "Tania Borealis",      "laUMa",      [],                                    new(false, false, false), 3.442),
        new("taniaAustralis",   "Tania Australis",     "muUMa",      [],                                    new(false, false, false), 3.066),
        new("alulaBorealis",    "Alula Borealis",      "nuUMa",      [],                                    new(false, false, false), 3.504),
        new("alulaAustralis",   "Alula Australis",     "xiUMa",      [],                                    new(false, false, false), 3.78),
        new("muscida",     "Muscida",                  "omiUMa",     [],                                    new(false, false, false), 3.362),
        new("elKophrah",   "El Kophrah",               "chUMa",      [],                                    new(false, false, false), 3.707),
        new("alcor",       "Alcor",                    "80Uma",      ["Saidak"],                            new(false, false, false), 4.01),
        new("kochab",      "Kochab",                   "beUMi",      [],                                    new(false, false, false), 2.078),
        new("pherkad",     "Pherkad",                  "gaUMi",      [],                                    new(false, false, false), 3.027),
        new("yildun",      "Yildun",                   "deUMi",      [],                                    new(false, false, false), 4.348),
        new("urodelus",    "Urodelus",                 "epUMi",      [],                                    new(false, false, false), 4.222),
        new("alifaAlFarkadain","Alifa Al Farkadain",   "zeUMi",      ["Farkadain","Pharkadain"],            new(false, false, false), 4.283),
        new("anwarAlFarkadain","Anwar al Farkadain",   "etUMi",      [],                                    new(false, false, false), 4.95),
        new("pherkadMinor","Pherkad Minor",            "11UMi",      [],                                    new(false, false, false), 5.024),
        new("suhailAlMuhlif","Suhail al Muhlif",       "ga-2Vel",    ["Regor"],                             new(false, false, false), 1.808),
        new("kooShe",      "Koo She",                  "deVel",      [],                                    new(false, false, false), 1.95),
        new("markeb",      "Markeb",                   "kaVel",      [],                                    new(false, true,  false), 2.464),
        new("alsuhail",    "Alsuhail",                 "laVel",      ["Suhail"],                            new(false, false, false), 2.226),
        new("peregrini",   "Peregrini",                "muVel",      ["Alherem"],                           new(false, false, false), 2.721),
        new("xestus",      "Xestus",                   "omiVel",     [],                                    new(false, false, false), 3.63),
        new("tseenKe",     "Tseen Ke",                 "phVel",      [],                                    new(false, false, false), 3.5),
        new("zavijava",    "Zavijava",                 "beVir",      ["Alaraph"],                           new(false, true,  false), 3.61),
        new("porrima",     "Porrima",                  "gaVir",      [],                                    new(false, true,  false), 2.74),
        new("auva",        "Auva",                     "deVir",      [],                                    new(false, false, false), 3.38),
        new("vindemiatrix","Vindemiatrix",             "epVir",      [],                                    new(false, true,  true), 2.83),
        new("heze",        "Heze",                     "zeVir",      [],                                    new(false, false, false), 3.4),
        new("zaniah",      "Zaniah",                   "etVir",      [],                                    new(false, true,  false), 3.89),
        new("syrma",       "Syrma",                    "ioVir",      [],                                    new(false, false, false), 4.1),
        new("khambalia",   "Khambalia",                "laVir",      [],                                    new(false, true,  false), 4.52),
        new("rijlAlAwwa",  "Rijl al Awwa",             "muVir",      ["Ril Alauva"],                        new(false, false, false), 3.9),
        new("anser",       "Anser",                    "alVul",      [],                                    new(false, false, false), 4.451),
    };
}
