<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
	<PlatformTarget>x64</PlatformTarget>
        <UseWPF>true</UseWPF>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace>EnigmaWin</RootNamespace>
        <AssemblyName>EnigmaWin</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
        <PackageReference Include="PDFsharp" Version="6.2.4" />
        <PackageReference Include="ScottPlot.WPF" Version="5.1.58" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3065.39" />
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Dapper" Version="2.1.35" />
    </ItemGroup>

    <ItemGroup>
      <None Include="Resources\i18n\**\*.strings">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Include="Resources\enneagram\*.csv">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <Link>res\enneagram\%(Filename)%(Extension)</Link>
      </None>
      <None Include="Resources\FactSheets\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <Content Include="Resources\swedll64.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Resources\enigma.db">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Resource Include="Resources\Fonts\EnigmaAstrology3.ttf" />
      <None Include="Resources\Fonts\EnigmaAstrology3.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <Link>Resources\Fonts\EnigmaAstrology3.ttf</Link>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Sources\Features\BlaSchema\UI\" />
      <Folder Include="Sources\Features\Progressive\PreNatal\UI\" />
      <Folder Include="Sources\Features\Progressive\PrimDir\UI\" />
      <Folder Include="Sources\Features\Progressive\Solar\UI\" />
      <Folder Include="Sources\Features\Radix\RadixAnalysis\Countings\UI\" />
    </ItemGroup>



</Project>
